#!/usr/bin/env python3
"""Turn a FOCAL source file into .dd directives for the interpreter.

    python3 mkprog.py focal/sum.fc asm/program.s

One character per 18-bit word, newline separated, zero terminated.
"""
import sys

src, dst = sys.argv[1], sys.argv[2]
out = ["; generated by mkprog.py from %s -- do not edit" % src, "TEXT:"]
for line in open(src).read().replace('\r\n', '\n').rstrip('\n').split('\n'):
    if not line.strip():
        continue
    esc = line.replace('\\', '\\\\').replace('"', '\\"')
    out.append('        .dd     "%s", 10' % esc)
out.append("        .dd     0")
open(dst, 'w').write("\n".join(out) + "\n")
print("%s: %d lines" % (dst, len(out) - 3))
