; generated by mkprog.py from focal/sum.fc -- do not edit
TEXT:
        .dd     "10 COMMENT TRIANGULAR NUMBERS AND A THREE WAY TEST", 10
        .dd     "20 SET A=7", 10
        .dd     "30 SET B=A*(A+1)/2", 10
        .dd     "40 TYPE \"SUM TO \", A, \" IS \", B, !", 10
        .dd     "50 IF (B-28) 80, 60, 80", 10
        .dd     "60 TYPE \"TWENTY EIGHT, AS EXPECTED\", !", 10
        .dd     "70 GOTO 90", 10
        .dd     "80 TYPE \"UNEXPECTED VALUE\", !", 10
        .dd     "90 SET C=(B-3)*2-A/2", 10
        .dd     "100 TYPE \"C = \", C, !", 10
        .dd     "110 TYPE \"NEG \", -C+1000, !", 10
        .dd     "120 QUIT", 10
        .dd     0
